name: publish to npmjs

on:
    pull_request:
        branches: ["main"]

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 2

            - name: git config user
              uses: snow-actions/git-config-user@v1.0.0

            - uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: npm set access level
              run: |
                  echo "//registry.npmjs.org/:_authToken=\${NPM_AUTH_TOKEN}" > ~/.npmrc
                  npm unpublish @adobe/ccweb-add-on-scaffolder@0.1.0
                  npm unpublish @adobe/ccweb-add-on-ssl@0.1.0
                  npm unpublish @adobe/ccweb-add-on-analytics@0.1.0
                  npm unpublish @adobe/ccweb-add-on-developer-terms@0.1.0
                  npm unpublish @adobe/ccweb-add-on-manifest@0.1.0
                  npm unpublish @adobe/ccweb-add-on-core@0.1.0
              env:
                  NPM_AUTH_TOKEN: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}
